### ISSUE TITLE
Conductor

### ISSUE THREAD

**Issue by ronoc** [mozilla/compatipede#1]
- [x] Read from SQS job queue
- [x] Request new tab from Jannah
  - User agent
  - Default screen size
- [x] Open URI
- [x] getResources()
- [x] getPluginsResults()
- [x] getScreenShot()
- [x] Collate all results and push a json results object to s3 and the DB

**Comment by dainis** [comment]
Couchdb has _changes using which clients can listen for changes(using filters it is possible to get only jobs with status new). Using couchdb there is no need for separate message queue
