### ISSUE TITLE
CSS analyzer

### ISSUE THREAD

**Issue by ronoc** [mozilla/compatipede#21]
- [ ] We need an analyser for CSS using work from Hallvord's scripts. 
- TODO more definition needed @seiflotfy ?

**Comment by dainis** [comment]
@hallvors how should auto test work, see if there is any difference or check if there are those platform specific css rules?

**Comment by hallvors** [comment]
For testing we should use some test cases and see if the plugin flags the styled elements. For example this one: http://hallvord.com/temp/moz/compatTesterTesting/csstest.html
(It's written to test an earlier slightly more sophisticated CSS analysis script - the one in Seif's "Compatipede 1", so it expects the tool to not flag elements that have standards-compatible equivalents to the -webkit- prefixed things. I'll add this logic later on.)

**Comment by ronoc** [comment]
This cannot land due to the architecture of the pluginmanager, the speed of this plugin, maybe we punt this to phase 2 ?
