### ISSUE TITLE
Ignore differences in query strings when comparing URLs

### ISSUE THREAD

**Issue by hallvors** [mozilla/compatipede#23]
A good number of sites use random strings as session identifiers and embed them in the URL, for example `?sessionid=longrandomstring`. To avoid flagging all such sites for redirecting to different URLs based on session/engine/UA we need to ignore any differences in the query string part of the URL.

**Comment by ronoc** [comment]
Ronoc: considering everything is really a resource, its not really feasible to just remove all query strings
Ronoc: consider index.php?controller=test&action=test2
Ronoc: unless we filter on specific key value pairs
Ronoc: sessionId, id etc
Ronoc: its very fuzzy
Ronoc: not sure how successfully it will be
Hallvord R. M. Steen: this is heuristics for sure
Hallvord R. M. Steen: it's just my experience that we have less false positives by ignoring query strings
Hallvord R. M. Steen: and while there probably are sites doing redirects to ?browser=bad or ?browser=good type query strings, there are many more doing sessionid stuff
Ronoc: okay so when matching ignore any query string diffs ?
Hallvord R. M. Steen: (in my experience - and YMMV)
Hallvord R. M. Steen: yes, that's what I want
Ronoc: okay cool
Hallvord R. M. Steen: :)
Hallvord R. M. Steen: I know we might miss something interesting - but the gain is much less noise so IMHO it's a good trade-off
