### ISSUE TITLE
Generate report from each run

### ISSUE THREAD

**Issue by ronoc** [mozilla/compatipede#26]
After each run through all campaigns the system should email a report to interested parties the results of the run. 

We should have a table for interested uses with their preference re emails. 
- [ ] Any errors during the run on what campaigns and what was the error message
- [ ] Each campaign that ran, plus the job details (UA, Engine)
- [ ] The results of any analysers that ran.

**Comment by ronoc** [comment]
@hallvors if you could let us know where you would like the report to end up and how it should be sent that would be swell.

**Comment by hallvors** [comment]
Setting it up initially to send to me, Mike and Karl by E-mail and documenting how to change those addresses should be pretty good for now.

**Comment by miketaylr** [comment]
> Setting it up initially to send to me, Mike and Karl by E-mail and documenting how to change those addresses should be pretty good for now.

I would say yes for me and Hallvord, let's let @karlcow opt himself in. ^_^

Maybe in the future we can set up a simple mailing list as the recipient, so instruction for how to update would be appreciated.

**Comment by ronoc** [comment]
We have a collection in the database called _compatipede-emails_.

It currently looks like this 

![screen shot 2016-02-02 at 20 37 52](https://cloud.githubusercontent.com/assets/203495/12763619/416888e8-c9ed-11e5-9f5a-b594205fba02.png)

@karlcow, let me know if you want to be removed, I will do so.

**Comment by karlcow** [comment]
@ronoc yup remove me for now.

**Comment by ronoc** [comment]
Just set the active field on your entry to false. That disables mails being
sent to you, easy to turn back on if you want to be spammed :)

**Comment by hallvors** [comment]
I'll do that for you @karlcow since it's my fault you're on the list :)

**Comment by ronoc** [comment]
Sorry I meant to say, I have turned off your email via that 'active' field.

**Comment by hallvors** [comment]
Ah, the English language fools foreigners like me and @karlcow again ;)
Thanks Conor.

**Comment by ronoc** [comment]
More like my command of it when tired is questionable :)
