### ISSUE TITLE
SMTP details for report sending

### ISSUE THREAD

**Issue by ronoc** [mozilla/compatipede#28]
We need SMTP details for sending emails from Compatipede ... ?

Alternatively we could use sendgrid, mandrill etc. 

Let us know so that we can update production.

**Comment by hallvors** [comment]
Awaiting response in https://bugzilla.mozilla.org/show_bug.cgi?id=1244082 ..

**Comment by hallvors** [comment]
@ronoc: https://bugzilla.mozilla.org/show_bug.cgi?id=1244082 was closed as fixed - sounds like they set up an SMTP service for the VM but didn't leave us any config details.. Can you get this working now, or do you need more info?

**Comment by ronoc** [comment]
hmm, are you happy to use an external service like sendgrid or mandrill ?

If so you will need to double check with your devops guys to make sure they don't have any issue with this and provide me the service details (i.e. make an account), we can then update the box for you with those details.

**Comment by hallvors** [comment]
I've set this up on the server now.
