### ISSUE TITLE
Configuration to disable saving resource data

### ISSUE THREAD

**Issue by hallvors** [mozilla/compatipede#41]
The implementation stores full HTML code of all web pages plus HTTP headers of all other resources. We probably won't use most of this data for anything, so a config setting to disable this would be good.

If we want it really granular we could make something like 

```
saveFullResourcesForTypes = ['text/html', ...]
saveMetaDataForTypes = ['video/mpeg', ...]
```

and let settings configured for specific campaigns or jobs override the defaults. Not sure if that's overkill or not..

**Comment by hallvors** [comment]
(Note that SlimerJS needs to be told which MIME types to give you the full body contents for, while PhantomJS needs some bug fix to roll into a release to support giving you resource bodies at all  - no idea about the status of that right now)

Anyway - @miketaylr  might want to have an opinion on whether this is a good idea or overkill.

**Comment by hallvors** [comment]
I've been looking into this. I think anything but a simple "saveResources" yes/no flag is overkill. I was considering creating a Compatipede command line argument that would be passed on all the way through Jannah and Boar to actually make Boar not record those details in the first place (saving some memory and efforts) but that's also going to be rather complicated due to the nice and modular architecture - many parts need changing for that solution to work. One single command line argument that controls whether resources are added to the database document here:
https://github.com/mozilla/compatipede/blob/47779fc6c360197f4f5135ec8b77d6ef2bc64b9f/lib/models/job.js#L70
is the simplest way to do it.

**Comment by miketaylr** [comment]
> I think anything but a simple "saveResources" yes/no flag is overkill.

Yeah, sounds good.
