### ISSUE TITLE
Ensure code choosing User-Agent respects issue labels classifying an issue as mobile

### ISSUE THREAD

**Issue by hallvors** [mozilla/compatipede#42]
Compatipede looks at the data submitted on webcompat.com when it imports issues from Github. It currently simply uses the User-Agent from the comment tag embedded in the issue source, regardless of the issue's tags. This matters because now and then reporters use a desktop browser to submit reports about mobile issues.

Code is here:
https://github.com/mozilla/compatipede/blob/master/lib/githubDispatcher.js#L69

@miketaylr - would be nice with some discussion of how to distinguish mobile-issues-reported-from-desktop-UAs and what UA strings to use.

**Comment by hallvors** [comment]
We may also want to change this code:
https://github.com/mozilla/compatipede/blob/813fdd7534c527df11ac68f53162943631b8617a/lib/models/campaign.js#L73
to make sure that if an issue is updated with labels indicating it's a mobile issue, the Compatipede DB is updated accordingly with a new User-Agent and type.

**Comment by miketaylr** [comment]
> @miketaylr - would be nice with some discussion of how to distinguish mobile-issues-reported-from-desktop-UAs and what UA strings to use.

Hm, I'm trying to think if we actually handle that from webcompat's side, or if it's just miscategorized (until a human fixes the label).
